# Generated by Django 5.0.4 on 2024-06-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
    ]
