# Generated by Django 5.0.4 on 2024-06-27 06:54

from django.db import migrations, models


def set_price(apps, schema_editor):
    MULTI = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for smartphone in smartphone_model.object.all():
        smartphone.price = MULTI * len(smartphone.brand)
        smartphone.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for smartphone in smartphone_model.object.all():
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

        smartphone.save()


def reverse_function(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for smartphone in smartphone_model.object.all():
        smartphone.category = smartphone_model._meta.get_field('category').default
        smartphone.category = smartphone_model._meta.get_field('price').default

        smartphone.save()


def set_all_columns(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
