# Generated by Django 5.0.4 on 2024-07-29 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(150)])),
                ('location', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)])),
                ('prize_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('surface_type', models.CharField(choices=[('Not Selected', 'Not Selected'), ('Clay', 'Clay'), ('Grass', 'Grass'), ('Hard Court', 'Hard Court')], default='Not Selected', max_length=12, validators=[django.core.validators.MaxLengthValidator(12)])),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
