# Generated by Django 5.0.4 on 2024-07-29 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('summary', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('date_played', models.DateTimeField()),
                ('players', models.ManyToManyField(related_name='matches', to='main_app.tennisplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main_app.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='main_app.tennisplayer')),
            ],
        ),
    ]
