# Generated by Django 5.0.4 on 2024-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
