# Generated by Django 5.0.4 on 2024-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_actor_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
