# Generated by Django 5.0.4 on 2024-07-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_movie_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
