# Generated by Django 5.0.6 on 2024-06-21 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in days'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 6, 21), null=True, verbose_name='Start Date'),
        ),
    ]
